main : gota.exe

gota.exe : gota.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

prego.exe : prego.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

editor.exe : editor.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

arm.exe : arm.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

