fm_instrument_table:

        ; 0  Original
        db      0,0,0,0
        db      0,0,0,0
        db      0,0,0,0
        db      0,0,0,0

        ; 1  Violin
        db      070h,020h,01Ch,0
        db      051h,0B4h,3,067h
        db      2,2,0Eh,0
        db      0,0,0,0

        ; 2  Guitar
        db      013h,011h,093h,080h
        db      0FFh,0FFh,021h,3
        db      0,0,0Ah,0
        db      0,0,0,0

        ; 3  Piano (acoustic grand)
        db      021h,031h,04Fh,0
        db      0F2h,0D2h,052h,073h
        db      0,0,6,0
        db      0,0,0,0

        ; 4  Flute 
        db      021h,0A1h,083h,040h
        db      074h,0A5h,017h,017h
        db      0,1,7,0
        db      0,0,0,0

        ; 5  Clarinet 
        db      032h,061h,09Ah,2
        db      051h,0B2h,01Bh,03Bh
        db      0,0,0Ch,0
        db      0,0,0,0

        ; 6  Oboe
        db      021h,024h,096h,0
        db      0F0h,0C0h,9,0Ah
        db      0,1,0Ah,0
        db      0,0,0,0

        ; 7  Trumpet 
        db      031h,062h,01Ch,080h
        db      041h,0C2h,0Bh,03Bh
        db      0,0,0Eh,0
        db      0,0,0,0

        ; 8  Organ
        db      1,031h,04Fh,0
        db      0F0h,090h,0FFh,0Fh
        db      0,0,6,0
        db      0,0,0,0

        ; 9  Horn (english)
        db      0B1h,0A2h,0C5h,0
        db      06Eh,0DBh,017h,0Eh
        db      0,1,2,0
        db      0,0,0,0

        ; 10 Synthesizer (strings)
        db      031h,062h,01Ch,2
        db      075h,054h,3,44h
        db      1,1,0Eh,0
        db      0,0,0,0

        ; 11 Harpsichord 
        db      031h,032h,08Eh,080h
        db      0F1h,0F3h,0F9h,0F9h
        db      0,0,0Ah,0
        db      0,0,0,0

        ; 12 Vibraphone 
        db      093h,091h,097h,080h
        db      0AAh,0ACh,012h,021h
        db      2,0,0Eh,0
        db      0,0,0,0

        ; 13 Synthesizer Bass
        db      011h,031h,5,0
        db      0F9h,0F1h,025h,034h
        db      0,0,0Ah,0
        db      0,0,0,0

        ; 14 Wood Bass (acoustic bass)
        db      1,0,0,0
        db      094h,083h,0B6h,026h
        db      0,0,1,0
        db      0,0,0,0

        ; 15 Electric Guitar 
        db      3,11h,05Eh,0
        db      0F5h,0F2h,071h,083h
        db      1,0,0Eh,0
        db      0,0,0,0



