guess_table:
        dd      03F1930F0h 
        dd      2+2
        dd      offset name_space_manbow

        dd      027B96E52h 
        dd      0+2
        dd      offset name_aleste

        dd      0E829BCEAh
        dd      0+2
        dd      offset name_super_runner

        dd      096BB9B9Dh
        dd      0+2
        dd      offset name_scramble_formation
        
        dd      02562AEA4h
        dd      5+2
        dd      offset name_xevious

        dd      0DA05ECD8h
        dd      5+2
        dd      offset name_zanac_ex
        
        dd      0BA414D43h
        dd      4+2
        dd      offset name_outrun
        
        dd      06C813EF9h
        dd      4+2
        dd      offset name_bubble_bobble
        
        dd      0B17626EEh
        dd      2+2
        dd      offset name_quarth
        
        dd      0B854C8F2h
        dd      2+2
        dd      offset name_quarth
        
        dd      07F551509h
        dd      3+2
        dd      offset name_treasure_usas
        
        dd      0AE07FC77h
        dd      3+2
        dd      offset name_vampire_killer
        
        dd      0DE8DC68Fh
        dd      2+2
        dd      offset name_kings_valley_2_msx2
        
        dd      0BEC3D518h
        dd      2+2
        dd      offset name_solid_snake
        
        dd      08BA31D3Eh
        dd      9+2
        dd      offset name_mahjong_2
        
        dd      0A4F1FB29h
        dd      2+2
        dd      offset name_solid_snake_english
        
        
        dd      08E150C70h
        dd      2+1
        dd      offset name_msxdos2

        dd      045DBFB63h
        dd      0+2
        dd      offset name_dragon_quest_1_msx1

        dd      07761C793h
        dd      0+2
        dd      offset name_cross_blaim
        
        dd      0FF017612h
        dd      8+2
        dd      offset name_fmpac_original
        
        dd      0E0A5BA1Ah
        dd      0+2
        dd      offset name_daiva
        
        dd      09D97F75Ch
        dd      0+2
        dd      offset name_craze
        
        dd      0C1F0F986h
        dd      0+2
        dd      offset name_king_knight
        
        dd      01D0648F2h
        dd      0+2
        dd      offset name_young_sherlock
        
        dd      0EB027E7Dh
        dd      0+2
        dd      offset name_3_eyed_one

        dd      0ACB3CCB7h
        dd      0+2
        dd      offset name_digital_devil_story

        dd      0706B9108h
        dd      4+2
        dd      offset name_dragon_slayer_4_msx1

        dd      00C43DEDEh
        dd      0+2
        dd      offset name_the_fairy_land_story

        dd      002E018E4h
        dd      0+2
        dd      offset name_final_zone

        dd      0F81F15F7h
        dd      5+2
        dd      offset name_golvellius

        dd      0EEF55FFCh
        dd      0+2
        dd      offset name_3_kingdoms

        dd      06B420EB7h
        dd      7+2
        dd      offset name_hydlide_2
        
        dd      0B33D8904h
        dd      2+2
        dd      offset name_nemesis_2

        dd      091D81846h
        dd      3+2
        dd      offset name_penguin_adventure

        dd      074679C4Bh
        dd      4+2
        dd      offset name_valis

        dd      0114F9637h
        dd      4+2
        dd      offset name_hydlide_3

        dd      01802082Dh
        dd      0+2
        dd      offset name_super_laydock_brazilian

        dd      0276FCCB8h
        dd      2+2
        dd      offset name_nemesis_3_korean

        dd      0FDC168FDh
        dd      3+2
        dd      offset name_nemesis

        dd      01778CC25h
        dd      2+2
        dd      offset name_nemesis_3

        dd      0EBDE8BFAh
        dd      3+2
        dd      offset name_shalom

        dd      009D46BDBh
        dd      6+2
        dd      offset name_xanadu

        dd      0B350DE3Bh
        dd      0+2
        dd      offset name_1942_msx1

        dd      08E4FB511h
        dd      0+2
        dd      offset name_animal_land

        dd      0F795DE6Fh
        dd      5+2
        dd      offset name_eggerland_mystery_2

        dd      0E299715Fh
        dd      5+2
        dd      offset name_eggerland_mystery_2

        dd      061E72787h
        dd      2+2
        dd      offset name_f1_spirit

        dd      0EA96C9E2h
        dd      4+2
        dd      offset name_fantasy_zone

        dd      0A6039EAEh
        dd      5+2
        dd      offset name_gall_force_fudeba

        dd      01F7BAC33h
        dd      5+2
        dd      offset name_gall_force

        dd      09D1356A1h
        dd      3+2
        dd      offset name_maze_of_galious

        dd      073049D87h
        dd      2+2
        dd      offset name_kings_valley_2_msx1
        
        dd      073689D87h
        dd      2+2
        dd      offset name_kings_valley_2_msx1
        
        dd      0E1290682h
        dd      0+2
        dd      offset name_mirai

        dd      09E398904h
        dd      0+2
        dd      offset name_nemesis_2_fudeba

        dd      08D1EDD30h
        dd      2+2
        dd      offset name_parodius

        dd      02DFD8BFDh
        dd      2+2
        dd      offset name_salamander

        dd      0D9B84E5Ah
        dd      0+2
        dd      offset name_vaxol

        dd      0DD7CDA08h
        dd      0+2
        dd      offset name_donkey_kong
                
        dd      0FF3874F0h
        dd      5+2
        dd      offset name_romancia

        dd      0B5D23D76h
        dd      3+2
        dd      offset name_nemesis_1_original

        dd      0

; name table

name_space_manbow:
        db      'Space Manbow$'

name_aleste:
        db      'Aleste$'

name_super_runner:
        db      'Super Runner$'

name_scramble_formation:
        db      'Scramble Formation$'

name_xevious:
        db      'Xevious$'

name_zanac_ex:
        db      'Zanac EX$'

name_outrun:
        db      'Out Run$'

name_bubble_bobble:
        db      'Bubble Bobble$'

name_quarth:
        db      'Quarth$'

name_treasure_usas:
        db      'The Treasure of Usas$'

name_vampire_killer:
        db      'Vampire Killer$'

name_solid_snake:
        db      'Solid Snake$'

name_mahjong_2:
        db      'Mahjong 2 (original)$'

name_solid_snake_english:
        db      'Solid Snake (english)$'

name_msxdos2:
        db      'MSX-DOS 2$'

name_nemesis_1_original:
        db      'Nemesis$'

name_dragon_quest_1_msx1:
        db      'Dragon Quest 1 (MSX1 version)$'

name_cross_blaim:
        db      'Cross Blaim$'

name_fmpac_original:
        db      'Original Panasonic FM-PAC$'

name_daiva:
        db      'Daiva, Story 4$'

name_romancia:
        db      'Romancia / Dragon Slayer Jr.$'

name_craze:
        db      'Craze$'

name_king_knight:
        db      'King Knight$'

name_young_sherlock:
        db      'Young Sherlock$'

name_3_eyed_one:
        db      'The Three Eyed One$'

name_digital_devil_story:
        db      'Digital Devil Story$'

name_dragon_slayer_4_msx1:
        db      'Dragon Slayer IV (MSX1 version)$'

name_the_fairy_land_story:
        db      'The Fairy Land Story$'

name_final_zone:
        db      'Final Zone$'

name_golvellius:
        db      'Golvellius$'

name_3_kingdoms:
        db      '3 Kingdoms$'

name_hydlide_2:
        db      'Hydlide 2$'

name_donkey_kong:
        db      'Donkey Kong$'

name_vaxol:
        db      'Vaxol$'

name_salamander:
        db      'Salamander$'

name_parodius:
        db      'Parodius$'

name_nemesis_2_fudeba:
        db      'Nemesis 2 (Ademir version, no SCC)$'

name_mirai:
        db      'Mirai$'

name_kings_valley_2_msx1:
        db      'King''s Valley 2 (MSX1 version)$'

name_kings_valley_2_msx2:
        db      'King''s Valley 2 (MSX2 version)$'

name_maze_of_galious:
        db      'Maze of Galious$'

name_gall_force:
        db      'Gall Force$'

name_gall_force_fudeba:
        db      'Gall Force (A&L Soft version)$'

name_fantasy_zone:
        db      'Fantasy Zone$'

name_f1_spirit:
        db      'F1 Spirit$'

name_eggerland_mystery_2:
        db      'Eggerland Mystery 2$'

name_animal_land:
        db      'Animal Land$'

name_1942_msx1:
        db      '1942 (MSX1 version)$'

name_xanadu:
        db      'Xanadu / Dragon Slayer II$'

name_shalom:
        db      'Shalom$'

name_nemesis_3:
        db      'Nemesis 3$'

name_nemesis:
        db      'Nemesis$'

name_nemesis_3_korean:
        db      'Nemesis 3 (Korean version)$'

name_super_laydock_brazilian:
        db      'Super Laydock (Brazilian version)$'

name_nemesis_2:
        db      'Nemesis 2$'

name_penguin_adventure:
        db      'Penguin Adventure$'

name_valis:
        db      'Valis, Fantasm Soldier$'

name_hydlide_3:
        db      'Hydlide 3$'

