extrn draw_gui: near
extrn start_gui: near

extrn psggraph: dword

extrn rendercounter: byte
extrn spritecounter: byte
extrn blitcounter: byte
extrn guicounter: byte
extrn psgcounter: byte
extrn vsynccounter: byte

extrn renderrate: dword
extrn spriterate: dword
extrn blitrate: dword
extrn guirate: dword
extrn psgrate: dword
extrn vsyncrate: dword

extrn turnoff_flag: dword
extrn patch__47: near
extrn uncompress_alf: near
