; -------------------------------------------------------------------- 
; BrMSX v:1.32                                                         
; Copyright (C) 1997 by Ricardo Bittencourt                            
; module: PRINTCB.ASM
; -------------------------------------------------------------------- 

        .386p
code32  segment para public use32
        assume cs:code32, ds:code32

include z80.inc
include debug.inc
include io.inc
include psetDD.inc
include psetDDCB.inc
include print.inc
include symdeb.inc

extrn prinXX: near
extrn prinDDCB: near
extrn isize: dword
extrn printmsgp: near
extrn printhex2p: near
extrn printhex4p: near

public psetDDxx
public psetDDCBxx

; --------------------------------------------------------------------

PRINTOP200      DD09,'ADD IX,BC$'
PRINTOP200      DD19,'ADD IX,DE$'
PRINTOP412      DD21,'LD IX,$'
PRINTOP422      DD22,'LD ($','),IX$'
PRINTOP200      DD23,'INC IX$'
PRINTOP200      DD24,'INC IXh$'
PRINTOP200      DD25,'DEC IXh$'
PRINTOP321      DD26,'LD IXh,$','$'
PRINTOP200      DD29,'ADD IX,IX$'
PRINTOP422      DD2A,'LD IX,($',')$'
PRINTOP200      DD2B,'DEC IX$'
PRINTOP200      DD2C,'INC IXl$'
PRINTOP200      DD2D,'DEC IXl$'
PRINTOP321      DD2E,'LD IXl,$','$'
PRINTOP321      DD34,'INC (IX+$',')$'
PRINTOP321      DD35,'DEC (IX+$',')$'
PRINTOP421      DD36,'LD (IX+$','),$'
PRINTOP200      DD39,'ADD IX,SP$'
PRINTOP100      DD40,'DD null prefix$'
PRINTOP100      DD41,'DD null prefix$'
PRINTOP100      DD42,'DD null prefix$'
PRINTOP100      DD43,'DD null prefix$'
PRINTOP200      DD44,'LD B,IXh$'
PRINTOP200      DD45,'LD B,IXl$'
PRINTOP321      DD46,'LD B,(IX+$',')$'
PRINTOP100      DD47,'DD null prefix$'
PRINTOP100      DD48,'DD null prefix$'
PRINTOP100      DD49,'DD null prefix$'
PRINTOP100      DD4A,'DD null prefix$'
PRINTOP100      DD4B,'DD null prefix$'
PRINTOP200      DD4C,'LD C,IXh$'
PRINTOP200      DD4D,'LD C,IXl$'
PRINTOP321      DD4E,'LD C,(IX+$',')$'
PRINTOP100      DD4F,'DD null prefix$'
PRINTOP100      DD50,'DD null prefix$'
PRINTOP100      DD51,'DD null prefix$'
PRINTOP100      DD52,'DD null prefix$'
PRINTOP100      DD53,'DD null prefix$'
PRINTOP200      DD54,'LD D,IXh$'
PRINTOP200      DD55,'LD D,IXl$'
PRINTOP321      DD56,'LD D,(IX+$',')$'
PRINTOP100      DD57,'DD null prefix$'
PRINTOP100      DD58,'DD null prefix$'
PRINTOP100      DD59,'DD null prefix$'
PRINTOP100      DD5A,'DD null prefix$'
PRINTOP100      DD5B,'DD null prefix$'
PRINTOP200      DD5C,'LD E,IXh$'
PRINTOP200      DD5D,'LD E,IXl$'
PRINTOP321      DD5E,'LD E,(IX+$',')$'
PRINTOP100      DD5F,'DD null prefix$'
PRINTOP200      DD60,'LD IXh,B$'
PRINTOP200      DD61,'LD IXh,C$'
PRINTOP200      DD62,'LD IXh,D$'
PRINTOP200      DD63,'LD IXh,E$'
PRINTOP200      DD64,'LD IXh,IXh$'
PRINTOP200      DD65,'LD IXh,IXl$'
PRINTOP321      DD66,'LD H,(IX+$',')$'
PRINTOP200      DD67,'LD IXh,A$'
PRINTOP200      DD68,'LD IXl,B$'
PRINTOP200      DD69,'LD IXl,C$'
PRINTOP200      DD6A,'LD IXl,D$'
PRINTOP200      DD6B,'LD IXl,E$'
PRINTOP200      DD6C,'LD IXl,IXh$'
PRINTOP200      DD6D,'LD IXl,IXl$'
PRINTOP321      DD6E,'LD L,(IX+$',')$'
PRINTOP200      DD6F,'LD IXl,A$'
PRINTOP321      DD70,'LD (IX+$','),B$'
PRINTOP321      DD71,'LD (IX+$','),C$'
PRINTOP321      DD72,'LD (IX+$','),D$'
PRINTOP321      DD73,'LD (IX+$','),E$'
PRINTOP321      DD74,'LD (IX+$','),H$'
PRINTOP321      DD75,'LD (IX+$','),L$'
PRINTOP100      DD76,'DD null prefix$'
PRINTOP321      DD77,'LD (IX+$','),A$'
PRINTOP100      DD78,'DD null prefix$'
PRINTOP100      DD79,'DD null prefix$'
PRINTOP100      DD7A,'DD null prefix$'
PRINTOP100      DD7B,'DD null prefix$'
PRINTOP200      DD7C,'LD A,IXh$'
PRINTOP200      DD7D,'LD A,IXl$'
PRINTOP321      DD7E,'LD A,(IX+$',')$'
PRINTOP100      DD7F,'DD null prefix$'
PRINTOP200      DD84,'ADD A,IXh$'
PRINTOP200      DD85,'ADD A,IXl$'
PRINTOP321      DD86,'ADD A,(IX+$',')$'
PRINTOP200      DD8C,'ADC A,IXh$'
PRINTOP200      DD8D,'ADC A,IXl$'
PRINTOP321      DD8E,'ADC A,(IX+$',')$'
PRINTOP200      DD94,'SUB IXh$'
PRINTOP200      DD95,'SUB IXl$'
PRINTOP321      DD96,'SUB (IX+$',')$'
PRINTOP200      DD9C,'SBC A,IXh$'
PRINTOP200      DD9D,'SBC A,IXl$'
PRINTOP321      DD9E,'SBC A,(IX+$',')$'
PRINTOP200      DDA4,'AND IXh$'
PRINTOP200      DDA5,'AND IXl$'
PRINTOP321      DDA6,'AND (IX+$',')$'
PRINTOP200      DDAC,'XOR IXh$'
PRINTOP200      DDAD,'XOR IXl$'
PRINTOP321      DDAE,'XOR (IX+$',')$'
PRINTOP200      DDB4,'OR IXh$'
PRINTOP200      DDB5,'OR IXl$'
PRINTOP321      DDB6,'OR (IX+$',')$'
PRINTOP200      DDBC,'CP IXh$'
PRINTOP200      DDBD,'CP IXl$'
PRINTOP321      DDBE,'CP (IX+$',')$'
PRINTOP200      DDE1,'POP IX$'
PRINTOP200      DDE3,'EX (SP),IX$'
PRINTOP200      DDE5,'PUSH IX$'
PRINTOP200      DDE9,'JP (IX)$'
PRINTOP200      DDF9,'LD SP,IX$'
PRINTOP100      DDNULL,'DD null prefix$'

PRINTOP42X      DDCB00,'LD B,RLC (IX+$',')$'
PRINTOP42X      DDCB01,'LD C,RLC (IX+$',')$'
PRINTOP42X      DDCB02,'LD D,RLC (IX+$',')$'
PRINTOP42X      DDCB03,'LD E,RLC (IX+$',')$'
PRINTOP42X      DDCB04,'LD H,RLC (IX+$',')$'
PRINTOP42X      DDCB05,'LD L,RLC (IX+$',')$'
PRINTOP42X      DDCB06,'RLC (IX+$',')$'
PRINTOP42X      DDCB07,'LD A,RLC (IX+$',')$'

PRINTOP42X      DDCB08,'LD B,RRC (IX+$',')$'
PRINTOP42X      DDCB09,'LD C,RRC (IX+$',')$'
PRINTOP42X      DDCB0A,'LD D,RRC (IX+$',')$'
PRINTOP42X      DDCB0B,'LD E,RRC (IX+$',')$'
PRINTOP42X      DDCB0C,'LD H,RRC (IX+$',')$'
PRINTOP42X      DDCB0D,'LD L,RRC (IX+$',')$'
PRINTOP42X      DDCB0E,'RRC (IX+$',')$'
PRINTOP42X      DDCB0F,'LD A,RRC (IX+$',')$'

PRINTOP42X      DDCB10,'LD B,RL (IX+$',')$'
PRINTOP42X      DDCB11,'LD C,RL (IX+$',')$'
PRINTOP42X      DDCB12,'LD D,RL (IX+$',')$'
PRINTOP42X      DDCB13,'LD E,RL (IX+$',')$'
PRINTOP42X      DDCB14,'LD H,RL (IX+$',')$'
PRINTOP42X      DDCB15,'LD L,RL (IX+$',')$'
PRINTOP42X      DDCB16,'RL (IX+$',')$'
PRINTOP42X      DDCB17,'LD A,RL (IX+$',')$'

PRINTOP42X      DDCB18,'LD B,RR (IX+$',')$'
PRINTOP42X      DDCB19,'LD C,RR (IX+$',')$'
PRINTOP42X      DDCB1A,'LD D,RR (IX+$',')$'
PRINTOP42X      DDCB1B,'LD E,RR (IX+$',')$'
PRINTOP42X      DDCB1C,'LD H,RR (IX+$',')$'
PRINTOP42X      DDCB1D,'LD L,RR (IX+$',')$'
PRINTOP42X      DDCB1E,'RR (IX+$',')$'
PRINTOP42X      DDCB1F,'LD A,RR (IX+$',')$'

PRINTOP42X      DDCB20,'LD B,SLA (IX+$',')$'
PRINTOP42X      DDCB21,'LD C,SLA (IX+$',')$'
PRINTOP42X      DDCB22,'LD D,SLA (IX+$',')$'
PRINTOP42X      DDCB23,'LD E,SLA (IX+$',')$'
PRINTOP42X      DDCB24,'LD H,SLA (IX+$',')$'
PRINTOP42X      DDCB25,'LD L,SLA (IX+$',')$'
PRINTOP42X      DDCB26,'SLA (IX+$',')$'
PRINTOP42X      DDCB27,'LD A,SLA (IX+$',')$'

PRINTOP42X      DDCB28,'LD B,SRA (IX+$',')$'
PRINTOP42X      DDCB29,'LD C,SRA (IX+$',')$'
PRINTOP42X      DDCB2A,'LD D,SRA (IX+$',')$'
PRINTOP42X      DDCB2B,'LD E,SRA (IX+$',')$'
PRINTOP42X      DDCB2C,'LD H,SRA (IX+$',')$'
PRINTOP42X      DDCB2D,'LD L,SRA (IX+$',')$'
PRINTOP42X      DDCB2E,'SRA (IX+$',')$'
PRINTOP42X      DDCB2F,'LD A,SRA (IX+$',')$'

PRINTOP42X      DDCB30,'LD B,SLL (IX+$',')$'
PRINTOP42X      DDCB31,'LD C,SLL (IX+$',')$'
PRINTOP42X      DDCB32,'LD D,SLL (IX+$',')$'
PRINTOP42X      DDCB33,'LD E,SLL (IX+$',')$'
PRINTOP42X      DDCB34,'LD H,SLL (IX+$',')$'
PRINTOP42X      DDCB35,'LD L,SLL (IX+$',')$'
PRINTOP42X      DDCB36,'SLL (IX+$',')$'
PRINTOP42X      DDCB37,'LD A,SLL (IX+$',')$'

PRINTOP42X      DDCB38,'LD B,SRL (IX+$',')$'
PRINTOP42X      DDCB39,'LD C,SRL (IX+$',')$'
PRINTOP42X      DDCB3A,'LD D,SRL (IX+$',')$'
PRINTOP42X      DDCB3B,'LD E,SRL (IX+$',')$'
PRINTOP42X      DDCB3C,'LD H,SRL (IX+$',')$'
PRINTOP42X      DDCB3D,'LD L,SRL (IX+$',')$'
PRINTOP42X      DDCB3E,'SRL (IX+$',')$'
PRINTOP42X      DDCB3F,'LD A,SRL (IX+$',')$'

PRINTOP42X      DDCB40,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB41,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB42,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB43,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB44,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB45,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB46,'BIT 0,(IX+$',')$'
PRINTOP42X      DDCB47,'BIT 0,(IX+$',')$'

PRINTOP42X      DDCB48,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB49,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4A,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4B,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4C,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4D,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4E,'BIT 1,(IX+$',')$'
PRINTOP42X      DDCB4F,'BIT 1,(IX+$',')$'

PRINTOP42X      DDCB50,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB51,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB52,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB53,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB54,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB55,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB56,'BIT 2,(IX+$',')$'
PRINTOP42X      DDCB57,'BIT 2,(IX+$',')$'

PRINTOP42X      DDCB58,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB59,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5A,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5B,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5C,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5D,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5E,'BIT 3,(IX+$',')$'
PRINTOP42X      DDCB5F,'BIT 3,(IX+$',')$'

PRINTOP42X      DDCB60,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB61,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB62,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB63,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB64,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB65,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB66,'BIT 4,(IX+$',')$'
PRINTOP42X      DDCB67,'BIT 4,(IX+$',')$'

PRINTOP42X      DDCB68,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB69,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6A,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6B,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6C,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6D,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6E,'BIT 5,(IX+$',')$'
PRINTOP42X      DDCB6F,'BIT 5,(IX+$',')$'

PRINTOP42X      DDCB70,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB71,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB72,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB73,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB74,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB75,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB76,'BIT 6,(IX+$',')$'
PRINTOP42X      DDCB77,'BIT 6,(IX+$',')$'

PRINTOP42X      DDCB78,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB79,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7A,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7B,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7C,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7D,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7E,'BIT 7,(IX+$',')$'
PRINTOP42X      DDCB7F,'BIT 7,(IX+$',')$'

PRINTOP42X      DDCB80,'LD B,RES 0,(IX+$',')$'
PRINTOP42X      DDCB81,'LD C,RES 0,(IX+$',')$'
PRINTOP42X      DDCB82,'LD D,RES 0,(IX+$',')$'
PRINTOP42X      DDCB83,'LD E,RES 0,(IX+$',')$'
PRINTOP42X      DDCB84,'LD H,RES 0,(IX+$',')$'
PRINTOP42X      DDCB85,'LD L,RES 0,(IX+$',')$'
PRINTOP42X      DDCB86,'RES 0,(IX+$',')$'
PRINTOP42X      DDCB87,'LD A,RES 0,(IX+$',')$'

PRINTOP42X      DDCB88,'LD B,RES 1,(IX+$',')$'
PRINTOP42X      DDCB89,'LD C,RES 1,(IX+$',')$'
PRINTOP42X      DDCB8A,'LD D,RES 1,(IX+$',')$'
PRINTOP42X      DDCB8B,'LD E,RES 1,(IX+$',')$'
PRINTOP42X      DDCB8C,'LD H,RES 1,(IX+$',')$'
PRINTOP42X      DDCB8D,'LD L,RES 1,(IX+$',')$'
PRINTOP42X      DDCB8E,'RES 1,(IX+$',')$'
PRINTOP42X      DDCB8F,'LD A,RES 1,(IX+$',')$'

PRINTOP42X      DDCB90,'LD B,RES 2,(IX+$',')$'
PRINTOP42X      DDCB91,'LD C,RES 2,(IX+$',')$'
PRINTOP42X      DDCB92,'LD D,RES 2,(IX+$',')$'
PRINTOP42X      DDCB93,'LD E,RES 2,(IX+$',')$'
PRINTOP42X      DDCB94,'LD H,RES 2,(IX+$',')$'
PRINTOP42X      DDCB95,'LD L,RES 2,(IX+$',')$'
PRINTOP42X      DDCB96,'RES 2,(IX+$',')$'
PRINTOP42X      DDCB97,'LD A,RES 2,(IX+$',')$'

PRINTOP42X      DDCB98,'LD B,RES 3,(IX+$',')$'
PRINTOP42X      DDCB99,'LD C,RES 3,(IX+$',')$'
PRINTOP42X      DDCB9A,'LD D,RES 3,(IX+$',')$'
PRINTOP42X      DDCB9B,'LD E,RES 3,(IX+$',')$'
PRINTOP42X      DDCB9C,'LD H,RES 3,(IX+$',')$'
PRINTOP42X      DDCB9D,'LD L,RES 3,(IX+$',')$'
PRINTOP42X      DDCB9E,'RES 3,(IX+$',')$'
PRINTOP42X      DDCB9F,'LD A,RES 3,(IX+$',')$'

PRINTOP42X      DDCBA0,'LD B,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA1,'LD C,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA2,'LD D,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA3,'LD E,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA4,'LD H,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA5,'LD L,RES 4,(IX+$',')$'
PRINTOP42X      DDCBA6,'RES 4,(IX+$',')$'
PRINTOP42X      DDCBA7,'LD A,RES 4,(IX+$',')$'

PRINTOP42X      DDCBA8,'LD B,RES 5,(IX+$',')$'
PRINTOP42X      DDCBA9,'LD C,RES 5,(IX+$',')$'
PRINTOP42X      DDCBAA,'LD D,RES 5,(IX+$',')$'
PRINTOP42X      DDCBAB,'LD E,RES 5,(IX+$',')$'
PRINTOP42X      DDCBAC,'LD H,RES 5,(IX+$',')$'
PRINTOP42X      DDCBAD,'LD L,RES 5,(IX+$',')$'
PRINTOP42X      DDCBAE,'RES 5,(IX+$',')$'
PRINTOP42X      DDCBAF,'LD A,RES 5,(IX+$',')$'

PRINTOP42X      DDCBB0,'LD B,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB1,'LD C,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB2,'LD D,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB3,'LD E,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB4,'LD H,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB5,'LD L,RES 6,(IX+$',')$'
PRINTOP42X      DDCBB6,'RES 6,(IX+$',')$'
PRINTOP42X      DDCBB7,'LD A,RES 6,(IX+$',')$'

PRINTOP42X      DDCBB8,'LD B,RES 7,(IX+$',')$'
PRINTOP42X      DDCBB9,'LD C,RES 7,(IX+$',')$'
PRINTOP42X      DDCBBA,'LD D,RES 7,(IX+$',')$'
PRINTOP42X      DDCBBB,'LD E,RES 7,(IX+$',')$'
PRINTOP42X      DDCBBC,'LD H,RES 7,(IX+$',')$'
PRINTOP42X      DDCBBD,'LD L,RES 7,(IX+$',')$'
PRINTOP42X      DDCBBE,'RES 7,(IX+$',')$'
PRINTOP42X      DDCBBF,'LD A,RES 7,(IX+$',')$'

PRINTOP42X      DDCBC0,'LD B,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC1,'LD C,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC2,'LD D,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC3,'LD E,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC4,'LD H,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC5,'LD L,SET 0,(IX+$',')$'
PRINTOP42X      DDCBC6,'SET 0,(IX+$',')$'
PRINTOP42X      DDCBC7,'LD A,SET 0,(IX+$',')$'

PRINTOP42X      DDCBC8,'LD B,SET 1,(IX+$',')$'
PRINTOP42X      DDCBC9,'LD C,SET 1,(IX+$',')$'
PRINTOP42X      DDCBCA,'LD D,SET 1,(IX+$',')$'
PRINTOP42X      DDCBCB,'LD E,SET 1,(IX+$',')$'
PRINTOP42X      DDCBCC,'LD H,SET 1,(IX+$',')$'
PRINTOP42X      DDCBCD,'LD L,SET 1,(IX+$',')$'
PRINTOP42X      DDCBCE,'SET 1,(IX+$',')$'
PRINTOP42X      DDCBCF,'LD A,SET 1,(IX+$',')$'

PRINTOP42X      DDCBD0,'LD B,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD1,'LD C,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD2,'LD D,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD3,'LD E,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD4,'LD H,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD5,'LD L,SET 2,(IX+$',')$'
PRINTOP42X      DDCBD6,'SET 2,(IX+$',')$'
PRINTOP42X      DDCBD7,'LD A,SET 2,(IX+$',')$'

PRINTOP42X      DDCBD8,'LD B,SET 3,(IX+$',')$'
PRINTOP42X      DDCBD9,'LD C,SET 3,(IX+$',')$'
PRINTOP42X      DDCBDA,'LD D,SET 3,(IX+$',')$'
PRINTOP42X      DDCBDB,'LD E,SET 3,(IX+$',')$'
PRINTOP42X      DDCBDC,'LD H,SET 3,(IX+$',')$'
PRINTOP42X      DDCBDD,'LD L,SET 3,(IX+$',')$'
PRINTOP42X      DDCBDE,'SET 3,(IX+$',')$'
PRINTOP42X      DDCBDF,'LD A,SET 3,(IX+$',')$'

PRINTOP42X      DDCBE0,'LD B,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE1,'LD C,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE2,'LD D,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE3,'LD E,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE4,'LD H,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE5,'LD L,SET 4,(IX+$',')$'
PRINTOP42X      DDCBE6,'SET 4,(IX+$',')$'
PRINTOP42X      DDCBE7,'LD A,SET 4,(IX+$',')$'

PRINTOP42X      DDCBE8,'LD B,SET 5,(IX+$',')$'
PRINTOP42X      DDCBE9,'LD C,SET 5,(IX+$',')$'
PRINTOP42X      DDCBEA,'LD D,SET 5,(IX+$',')$'
PRINTOP42X      DDCBEB,'LD E,SET 5,(IX+$',')$'
PRINTOP42X      DDCBEC,'LD H,SET 5,(IX+$',')$'
PRINTOP42X      DDCBED,'LD L,SET 5,(IX+$',')$'
PRINTOP42X      DDCBEE,'SET 5,(IX+$',')$'
PRINTOP42X      DDCBEF,'LD A,SET 5,(IX+$',')$'

PRINTOP42X      DDCBF0,'LD B,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF1,'LD C,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF2,'LD D,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF3,'LD E,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF4,'LD H,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF5,'LD L,SET 6,(IX+$',')$'
PRINTOP42X      DDCBF6,'SET 6,(IX+$',')$'
PRINTOP42X      DDCBF7,'LD A,SET 6,(IX+$',')$'

PRINTOP42X      DDCBF8,'LD B,SET 7,(IX+$',')$'
PRINTOP42X      DDCBF9,'LD C,SET 7,(IX+$',')$'
PRINTOP42X      DDCBFA,'LD D,SET 7,(IX+$',')$'
PRINTOP42X      DDCBFB,'LD E,SET 7,(IX+$',')$'
PRINTOP42X      DDCBFC,'LD H,SET 7,(IX+$',')$'
PRINTOP42X      DDCBFD,'LD L,SET 7,(IX+$',')$'
PRINTOP42X      DDCBFE,'SET 7,(IX+$',')$'
PRINTOP42X      DDCBFF,'LD A,SET 7,(IX+$',')$'

; --------------------------------------------------------------------

code32          ends
                end

