scr2undoc_table: 
                ; 0 (LIKE)
                dd      0
                dd      0
                dd      0

                ; 1 (marujo)
                dd      0
                dd      800h
                dd      -800h

                ; 2 (Thing Bounces Back)
                dd      0
                dd      0
                dd      1000h

                ; 3 (common)
                dd      0
                dd      800h
                dd      800h

