decode.exe : decode.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

encode.exe : encode.c
	gcc $^ -o $@ -I/djgpp/allegro2/include -L/djgpp/allegro2/lib -lalleg -Wall -O2

