extrn printmsg:near
extrn printnul:near
extrn printasc:near
extrn printhex2:near
extrn printhex4:near
extrn printspace:near
extrn crlf: near
extrn getchar: near
extrn gethex4: near
extrn testkbd: near
extrn setgraphmode: near
extrn settextmode: near
extrn toupper: near
extrn open_file: near
extrn read_file: near
extrn turnon_irq: near
extrn turnoff_irq: near
extrn turnon_kb_irq: near
extrn turnoff_kb_irq: near
extrn read_size_file: near
extrn exit_now: dword
extrn framerate: dword
extrn on_off: dword
extrn set_border_color: near
extrn videomode: dword
extrn measurespeed: near
extrn clockrate: byte
extrn printdecimal: near
extrn bargraphmode: dword
extrn set_cursor_position: near
extrn convhex4: near
extrn tmphex4: byte
extrn tmphex2: byte
extrn write_file: near
extrn close_file: near
extrn create_file: near
extrn cpupaused: dword
extrn fill_palette: near
extrn gui_palette: byte
extrn palette: byte
extrn set_border_color_dark: near
extrn wait_vsync: near
extrn find_first: near
extrn find_next: near
extrn set_correct_palette: near
extrn setkb: near
extrn noled: dword
extrn set_SMS_color: near
extrn set_GG_color: near
extrn set_SMS_palette: near
extrn savenow: dword
extrn loadnow: dword
extrn savesnap: dword
extrn currentpalette: dword
extrn dirty_palette: dword
extrn set_border_color: near
extrn sg1000_high_palette: byte
extrn keyboardtable_sc3000: byte
extrn keyboard_actual: dword
extrn keyboard_ext_sc3000: byte
extrn keyboard_extended: dword
extrn wait_next_vsync: near
extrn keyboardtable_coleco: byte
extrn keyboard_ext_coleco: byte
extrn time_base: dword
extrn frames_drawed: dword
extrn fps_counter: dword
extrn reset_autoframe: near
