
keyboardtable:
	key_00: db 0,0
	key_01: db 1,BIT_4      ; ESC
	key_02: db 0,0      ; 1
	key_03: db 0,0      ; 2
	key_04: db 0,0      ; 3
	key_05: db 0,0      ; 4
	key_06: db 0,0      ; 5
	key_07: db 0,0      ; 6
	key_08: db 0,0      ; 7
	key_09: db 0,0; 1,BIT_0      ; 8
	key_0A: db 0,0; 1,BIT_1      ; 9
	key_0B: db 0,BIT_0      ; 0
	key_0C: db 0,0; 1,BIT_2      ; -
	key_0D: db 0,0; 1,BIT_3      ; =
	key_0E: db 7,BIT_5      ; BACKSPACE
	key_0F: db 1,BIT_2      ; TAB
	key_10: db 4,BIT_6      ; Q
	key_11: db 5,BIT_4      ; W
	key_12: db 0,BIT_6      ; E
	key_13: db 0,0      ; R
	key_14: db 5,BIT_1      ; T
	key_15: db 5,BIT_6      ; Y
	key_16: db 5,BIT_2      ; U
	key_17: db 3,BIT_6      ; I
	key_18: db 4,BIT_4      ; O
	key_19: db 4,BIT_5      ; P
	key_1A: db 0,0
	key_1B: db 0,0
	key_1C: db 7,BIT_7      ; ENTER
	key_1D: db 0,BIT_4      ; CONTROL;;
	key_1E: db 0,0 ;2,BIT_6      ; A
	key_1F: db 1,BIT_0      ; S
	key_20: db 0,BIT_7      ; D
	key_21: db 1,BIT_1      ; F
	key_22: db 3,BIT_4      ; G
	key_23: db 3,BIT_5      ; H
	key_24: db 3,BIT_7      ; J
	key_25: db 4,BIT_0      ; K
	key_26: db 4,BIT_1      ; L
	key_27: db 0,0; 1,BIT_7      ; ;
	key_28: db 0,0 ;2,BIT_0      ; '
	key_29: db 0,0
	key_2A: db 6,BIT_0      ; LEFT SHIFT
	key_2B: db 0,0
	key_2C: db 5,BIT_7      ; Z
	key_2D: db 5,BIT_5      ; X
	key_2E: db 3,BIT_0      ; C
	key_2F: db 5,BIT_3      ; V
	key_30: db 0,0; 2,BIT_7      ; B
	key_31: db 4,BIT_3      ; N
	key_32: db 4,BIT_2      ; M
	key_33: db 0,0; 2,BIT_2      ; ,
	key_34: db 0,0; 2,BIT_3      ; .
	key_35: db 0,0; 2,BIT_4      ; /
	key_36: db 6,BIT_0      ; RIGHT SHIFT
	key_37: db 0,0
	key_38: db 0,BIT_5      ; LEFT ALT ;;
	key_39: db 2,BIT_7      ; SPACEBAR
	key_3A: db 1,BIT_3      ; CAPS LOCK
	key_3B: db 6,BIT_5      ; F1
	key_3C: db 6,BIT_6      ; F2
	key_3D: db 6,BIT_7      ; F3
	key_3E: db 7,BIT_0      ; F4
	key_3F: db 7,BIT_1      ; F5
	key_40: db 0,0
	key_41: db 0,0
	key_42: db 0,0
	key_43: db 0,0
	key_44: db 0,0
	key_45: db 0,0
	key_46: db 0,0
	key_47: db 8,BIT_1      ; HOME
	key_48: db 0,BIT_0      ; UP ;;
	key_49: db 7,BIT_4      ; PAGE UP
	key_4A: db 0,0
	key_4B: db 0,BIT_2      ; LEFT ;;
	key_4C: db 0,0
	key_4D: db 0,BIT_3      ; RIGHT ;;
	key_4E: db 0,0
	key_4F: db 0,0
	key_50: db 0,BIT_1      ; DOWN ;;
	key_51: db 7,BIT_6      ; PAGE DOWN
	key_52: db 8,BIT_2      ; INSERT
	key_53: db 8,BIT_3      ; DELETE
	key_54: db 0,0
	key_55: db 0,0
	key_56: db 0,0
	key_57: db 0,0
	key_58: db 0,0
	key_59: db 0,0
	key_5A: db 0,0
	key_5B: db 0,0
	key_5C: db 0,0
	key_5D: db 0,0
	key_5E: db 0,0
	key_5F: db 0,0
	key_60: db 0,0
	key_61: db 0,0
	key_62: db 0,0
	key_63: db 0,0
	key_64: db 0,0
	key_65: db 0,0
	key_66: db 0,0
	key_67: db 0,0
	key_68: db 0,0
	key_69: db 0,0
	key_6A: db 0,0
	key_6B: db 0,0
	key_6C: db 0,0
	key_6D: db 0,0
	key_6E: db 0,0
	key_6F: db 0,0
	key_70: db 0,0
	key_71: db 0,0
	key_72: db 0,0
	key_73: db 0,0
	key_74: db 0,0
	key_75: db 0,0
	key_76: db 0,0
	key_77: db 0,0
	key_78: db 0,0
	key_79: db 0,0
	key_7A: db 0,0
	key_7B: db 0,0
	key_7C: db 0,0
	key_7D: db 0,0
	key_7E: db 0,0
	key_7F: db 0,0
