
keyboardtable_coleco:
	 db 0,0
	 db 0,0      ; ESC
	 db 2,BIT_1  ; 1
	 db 2,BIT_2  ; 2
	 db 2,BIT_3  ; 3
	 db 2,BIT_4  ; 4
	 db 2,BIT_5  ; 5
	 db 2,BIT_6  ; 6
	 db 2,BIT_7      ; 7
	 db 3,BIT_0    ; 8
	 db 3,BIT_1    ; 9
	 db 2,BIT_0    ; 0
	 db 0,0    ; -
	 db 0,0    ; =
	 db 0,0      ; BACKSPACE
	 db 0,0          ; TAB
	 db 0,0      ; Q
	 db 0,0      ; W
	 db 0,0      ; E
	 db 0,0      ; R
	 db 0,0      ; T
	 db 0,0      ; Y
	 db 0,0      ; U
	 db 0,0      ; I
	 db 0,0      ; O
	 db 0,0      ; P
	 db 0,0      ; [
	 db 0,0      ; ]
	 db 3,BIT_2      ; ENTER
	 db 0,BIT_4    ; CONTROL
	 db 0,0      ; A
	 db 0,0      ; S
	 db 0,0      ; D
	 db 0,0      ; F
	 db 0,0      ; G
	 db 0,0      ; H
	 db 0,0      ; J
	 db 0,0      ; K
	 db 0,0      ; L
	 db 0,0      ; ;
	 db 0,0      ; '
	 db 0,0
	 db 0,0      ; LEFT SHIFT
	 db 0,0
	 db 0,0      ; Z
	 db 0,0      ; X
	 db 0,0      ; C
	 db 0,0      ; V
	 db 0,0      ; B
	 db 0,0      ; N
	 db 0,0      ; M
	 db 0,0      ; ,
	 db 0,0      ; .
	 db 0,0      ; /
	 db 0,0      ; RIGHT SHIFT
	 db 0,0
	 db 0,BIT_5      ; LEFT ALT ;;
	 db 3,BIT_3      ; SPACEBAR
	 db 0,0      ; CAPS LOCK
	 db 0,0      ; F1
	 db 0,0      ; F2
	 db 0,0      ; F3
	 db 0,0      ; F4
	 db 0,0      ; F5
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0      ; HOME
	 db 0,BIT_0    ; UP ;;
	 db 0,0      ; PAGE UP
	 db 0,0
	 db 0,BIT_2;        ; LEFT ;;
	 db 0,0
	 db 0,BIT_3;        ; RIGHT ;;
	 db 0,0
	 db 0,0
	 db 0,BIT_1       ; DOWN ;;
	 db 0,0      ; PAGE DOWN
	 db 0,0      ; INSERT
	 db 0,0      ; DELETE
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
