
keyboardtable_sc3000:
	 db 0,0
	 db 0,0      ; ESC
	 db 0,BIT_0  ; 1
	 db 1,BIT_0  ; 2
	 db 2,BIT_0  ; 3
	 db 3,BIT_0  ; 4
	 db 4,BIT_0  ; 5
	 db 5,BIT_0  ; 6
	 db 6,BIT_0      ; 7
	 db 8+0,BIT_0    ; 8
	 db 8+1,BIT_0    ; 9
	 db 8+2,BIT_0    ; 0
	 db 8+3,BIT_0    ; -
	 db 8+4,BIT_0    ; =
	 db 3,BIT_4      ; BACKSPACE
	 db 0,0          ; TAB
	 db 0,BIT_1      ; Q
	 db 1,BIT_1      ; W
	 db 2,BIT_1      ; E
	 db 3,BIT_1      ; R
	 db 4,BIT_1      ; T
	 db 5,BIT_1      ; Y
	 db 6,BIT_1      ; U
	 db 0,BIT_7      ; I
	 db 1,BIT_7      ; O
	 db 2,BIT_7      ; P
	 db 4,BIT_7      ; [
	 db 4,BIT_6      ; ]
	 db 5,BIT_6      ; ENTER
	 db 8+5,BIT_3    ; CONTROL
	 db 0,BIT_2      ; A
	 db 1,BIT_2      ; S
	 db 2,BIT_2      ; D
	 db 3,BIT_2      ; F
	 db 4,BIT_2      ; G
	 db 5,BIT_2      ; H
	 db 6,BIT_2      ; J
	 db 0,BIT_6      ; K
	 db 1,BIT_6      ; L
	 db 2,BIT_6      ; ;
	 db 3,BIT_6      ; '
	 db 0,0
	 db 8+6,BIT_3      ; LEFT SHIFT
	 db 0,0
	 db 0,BIT_3      ; Z
	 db 1,BIT_3      ; X
	 db 2,BIT_3      ; C
	 db 3,BIT_3      ; V
	 db 4,BIT_3      ; B
	 db 5,BIT_3      ; N
	 db 6,BIT_3      ; M
	 db 0,BIT_5      ; ,
	 db 1,BIT_5      ; .
	 db 2,BIT_5      ; /
	 db 8+6,BIT_3      ; RIGHT SHIFT
	 db 0,0
	 db 0,0      ; LEFT ALT ;;
	 db 1,BIT_4      ; SPACEBAR
	 db 1,BIT_3      ; CAPS LOCK
	 db 0,0      ; F1
	 db 0,0      ; F2
	 db 0,0      ; F3
	 db 0,0      ; F4
	 db 0,0      ; F5
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0      ; HOME
	 db 6,BIT_6  ; UP ;;
	 db 0,0      ; PAGE UP
	 db 0,0
	 db 5,BIT_5      ; LEFT ;;
	 db 0,0
	 db 6,BIT_5      ; RIGHT ;;
	 db 0,0
	 db 0,0
	 db 4,BIT_5      ; DOWN ;;
	 db 0,0      ; PAGE DOWN
	 db 0,0      ; INSERT
	 db 0,0      ; DELETE
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
	 db 0,0
