	dd      0 ;-1
sprite_table:
	dd      8 ;0
	dd      8 ;1
	dd      8 ;2
	dd      8 ;3
	dd      8 ;4
	dd      8 ;5
	dd      8 ;6
	dd      8+8*8 ;7
	dd      8 ;8
	dd      8 ;9
	dd      8 ;10
	dd      8 ;11
	dd      8 ;12
	dd      8 ;13
	dd      8 ;14
	dd      8 ;15
	dd      8 ;16

sprite_line_raster:
	dd      8*0
	dd      8*1
	dd      8*2
	dd      8*3
	dd      8*4
	dd      8*5
	dd      8*6
	dd      8*7
	dd      128+8*0
	dd      128+8*1
	dd      128+8*2
	dd      128+8*3
	dd      128+8*4
	dd      128+8*5
	dd      128+8*6
	dd      128+8*7

sprite_line_zoomed:
	dd      8*0
	dd      8*0
	dd      8*1
	dd      8*1
	dd      8*2
	dd      8*2
	dd      8*3
	dd      8*3
	dd      8*4
	dd      8*4
	dd      8*5
	dd      8*5
	dd      8*6
	dd      8*6
	dd      8*7
	dd      8*7
	dd      128+8*0
	dd      128+8*0
	dd      128+8*1
	dd      128+8*1
	dd      128+8*2
	dd      128+8*2
	dd      128+8*3
	dd      128+8*3
	dd      128+8*4
	dd      128+8*4
	dd      128+8*5
	dd      128+8*5
	dd      128+8*6
	dd      128+8*6
	dd      128+8*7
	dd      128+8*7

